//
//  MainInteractor.swift
//  RickMortyApi
//
//  Created ISAAC DAVID SANTIAGO on 23/08/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainInteractor: MainInteractorProtocol {

    weak var presenter: MainPresenterProtocol?
}
