//
//  MainProtocols.swift
//  RickMortyApi
//
//  Created ISAAC DAVID SANTIAGO on 23/08/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {

}
//MARK: Presenter -
protocol MainPresenterProtocol: class {

}

//MARK: Interactor -
protocol MainInteractorProtocol: class {

  var presenter: MainPresenterProtocol?  { get set }
}

//MARK: View -
protocol MainViewProtocol: class {

  var presenter: MainPresenterProtocol?  { get set }
}
